### ISSUE TITLE
Consistent renaming

### ISSUE THREAD

**Issue by jakobsj** [CUQI-DTU/CUQIpy#192]
e.g.
- [ ]  1D vs _1D
- [ ]  Cauchy_diff Diff #229  #231 
- [ ]  Fenics eg prepend Matern by fenics?
- [ ]  Problem/Model/Distb at end?
- [ ]  KL zoo
- [ ]  MH or MetropolisHastings #230  #232
- [ ]  2x ULA
- [ ] rename Linear_RTO

**Comment by amal-ghamdi** [comment]
e.g.
- [x]  1D vs _1D (only _deconv_1D still have this name)
- [x]  Cauchy_diff Diff #229  #231 (done #231 to be closed in this sprint 21)
- [x]  Fenics eg prepend Matern by fenics? (created issue https://github.com/CUQI-DTU/CUQIpy-FEniCS/issues/66)
- [ ]  Problem/Model/Distb at end?
- [x]  KL zoo n
- [x]  MH or MetropolisHastings #230  #232 (two issues are closed, one more update is needed in paper 2 repo #https://github.com/CUQI-DTU/Paper-CUQIpy-2-PDE/issues/42)
- [x]  2x ULA (this item is addressed by closing #234 which is part of this sprint 21, we have ULA and UGLA now) 
- [x] rename Linear_RTO (created issue #281)

**Comment by amal-ghamdi** [comment]
@jakobsj @nabriis 

I think this issue can be closed. I broke it down to smaller issues  (in some cases I noted that the work for the item is done) as explained in my comment above.

**Comment by nabriis** [comment]
LGTM

**Comment by jakobsj** [comment]
Agreed, thanks!
