### ISSUE TITLE
PDE support roadmap (Part I: potential mini-projects planned in Word document)

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#346]
- Integrate with SW package e.g. Sundials perhaps via Assimulo or pytorch feincs, etc 

- [ ] Minimal example fenics adjoint
- [ ] prepare document for roadmap
- [ ] prepare dynamic roadmap (could be something like this)
- [ ] Minimal example assimulo
