### ISSUE TITLE
Regularized Gaussian: TV with Gibbs and more

### ISSUE THREAD

**Issue by jeverink** [CUQI-DTU/CUQIpy#585]
Roadmap for the planned features for the Regularized Gaussian distributions: (Each planned as their own PR)
- [x] 1: Add ADMM solver
- [x] 2: Add TV as option for RegularizedGaussian, see #575 
- [x] 3: Add Conjugacy for TV, see #587 
- [x] 4: Add nonnegativity constrained TV with Gibbs #612 

Add additional constraints:
- [x] 5: Add Monotonicity constraints, see #618 

Optional considerations:
- [x] Solver choice: Scipy linear least squares for nonnegativity and box constraints
- [ ] Solver choices: others?
- [ ] Write a how-to guide #616 
- [ ] Possible unification of the penalty terms, see #584

**Comment by chaozg** [comment]
As suggested by @jeverink, this issue can be safely closed as 
- all core sub-issues are created and fixed
- optional sub-issues are being tracked separately.
