### ISSUE TITLE
Feature wish list for workshop

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#96]
- [x] CUQIpy pip release (see #97)
- [x] CIL plugin https://github.com/CUQI-DTU/CUQIpy-CIL/issues/1
- [x] FEniCS plugin
- [x] PyTorch plugin
- [x] A single better Gaussian #39 
- [ ] Allow all samplers to work with Gibbs #34 
- [ ] Add more automatic sampler choices to BayesianProblem #95
- [ ] CUQIpy conda release (#98)
